PKGDIR           ?= ../..
L4DIR            ?= $(PKGDIR)/../..
PLUGIN           := input-libinput
PLUGIN_STATIC_ONLY := y
SRC_CC           := input_libinput.cc
SRC_CC_IS_CXX11 := y
REQUIRES_LIBS   += input

include $(PKGDIR)/plugins/plugin.mk
