L4Re - L4 Runtime Environment: L4::Debugger Class Reference
L4::Debugger Class Reference
C++ debugger interface.
Public Member Functions
l4_msgtag_t set_object_name (const char *name, l4_utcb_t *utcb=l4_utcb()) throw ()
Set the name of a kernel object.
unsigned long global_id (l4_utcb_t *utcb=l4_utcb()) throw ()
Get the globally unique ID of the object behind a capability.
unsigned long kobj_to_id (l4_addr_t kobjp, l4_utcb_t *utcb=l4_utcb()) throw ()
Get the globally unique ID of the object behind the kobject pointer.
int query_log_typeid (const char *name, unsigned idx, l4_utcb_t *utcb=l4_utcb()) throw ()
int query_log_name (unsigned idx, char *name, unsigned namelen, char *shortname, unsigned shortnamelen, l4_utcb_t *utcb=l4_utcb()) throw ()
l4_msgtag_t switch_log (const char *name, unsigned on_off, l4_utcb_t *utcb=l4_utcb()) throw ()
l4_msgtag_t get_object_name (unsigned id, char *name, unsigned size, l4_utcb_t *utcb=l4_utcb()) throw ()
Get name of object with Id id.
Public Member Functions inherited from L4::Kobject
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Additional Inherited Members
Protected Types inherited from L4::Kobject_t< Debugger, Kobject, L4_PROTO_DEBUGGER >
typedef Debugger Class
The target interface type (inheriting from Kobject_t)
typedef Typeid::Iface< PROTO,
Debugger > __Iface
The interface description for the derived class.
typedef Typeid::Merge_list
< Typeid::Iface_list< __Iface >
, typename
Kobject::__Iface_list > __Iface_list
The list of all RPC interfaces provided directly or through inheritance.
Protected Member Functions inherited from L4::Kobject_t< Debugger, Kobject, L4_PROTO_DEBUGGER >
L4::Cap< Class > c () const
Get the capability to ourselves.
Protected Member Functions inherited from L4::Kobject
l4_cap_idx_t cap () const throw ()
Return capability selector.
Static Protected Member Functions inherited from L4::Kobject_t< Debugger, Kobject, L4_PROTO_DEBUGGER >
static void __check_protocols__ ()
Helper to check for protocol conflicts.
Detailed Description
C++ debugger interface.
Attention
This API is subject to change! Do not rely on it in production code.
Include File
#include <l4/sys/debugger>
Definition at line 39 of file debugger.
Member Function Documentation
l4_msgtag_t L4::Debugger::get_object_name (unsigned id, char * name, unsigned size, l4_utcb_t * utcb = l4_utcb()) throw () inline
Get name of object with Id id.
Parameters
id Id of the object whose name is asked.
[out] name Buffer to copy the name into. The buffer must be allocated by the caller.
size Length of the name buffer.
utcb The UTCB to use for the operation.
Returns
Syscall return tag
Definition at line 140 of file debugger.
References L4::Kobject::cap().
unsigned long L4::Debugger::global_id (l4_utcb_t * utcb = l4_utcb()) throw () inline
Get the globally unique ID of the object behind a capability.
Parameters
utcb The UTCB to use for the operation.
Return values
~0UL The capability is invalid.
>=0 The global debugger id.
Definition at line 66 of file debugger.
References L4::Kobject::cap().
unsigned long L4::Debugger::kobj_to_id (l4_addr_t kobjp, l4_utcb_t * utcb = l4_utcb()) throw () inline
Get the globally unique ID of the object behind the kobject pointer.
Parameters
kobjp Kobject pointer
utcb The UTCB to use for the operation.
Return values
~0UL The capability or the Kobject pointer are invalid.
>=0 The globally unique id.
Definition at line 77 of file debugger.
References L4::Kobject::cap().
int L4::Debugger::query_log_name (unsigned idx, char * name, unsigned namelen, char * shortname, unsigned shortnamelen, l4_utcb_t * utcb = l4_utcb()) throw () inline
Parameters
idx ID to query.
[out] name Buffer to copy name to. The buffer must be allocated by the caller.
namelen Buffer length of name.
[out] shortname Buffer to copy shortname to. The buffer must be allocated by the caller.
shortnamelen Buffer length of shortname.
utcb The UTCB to use for the operation.
Return values
0 Success
<0 Error
Definition at line 108 of file debugger.
References L4::Kobject::cap().
int L4::Debugger::query_log_typeid (const char * name, unsigned idx, l4_utcb_t * utcb = l4_utcb()) throw () inline
Parameters
name Name to query for.
idx Idx to start searching, start with 0
utcb The UTCB to use for the operation.
Return values
>=0 Id
<0 Error
Definition at line 90 of file debugger.
References L4::Kobject::cap().
l4_msgtag_t L4::Debugger::set_object_name (const char * name, l4_utcb_t * utcb = l4_utcb()) throw () inline
Set the name of a kernel object.
Parameters
name Name
utcb The UTCB to use for the operation.
Returns
System call return tag.
Definition at line 55 of file debugger.
References L4::Kobject::cap().
l4_msgtag_t L4::Debugger::switch_log (const char * name, unsigned on_off, l4_utcb_t * utcb = l4_utcb()) throw () inline
Parameters
name Name of the log type.
on_off 1: turn log on, 0: turn log off
utcb The UTCB to use for the operation.
Returns
Syscall return tag
Definition at line 125 of file debugger.
References L4::Kobject::cap().
The documentation for this class was generated from the following file:
l4/sys/debugger