L4Re - L4 Runtime Environment: L4::Ipc_svr::Timeout_queue Class Reference
L4::Ipc_svr::Timeout_queue Class Reference
Client/Server IPC Framework » Server-Side IPC framework
Timeout queue to be used in l4re server loop.
Public Types
typedef L4::Ipc_svr::Timeout Timeout
Provide a local definition of Timeout for backward compat.
Public Member Functions
Timeout_queue ()
Creates an empty timeout queue.
bool timeout_expired (l4_kernel_clock_t now) const
Determine if a timeout has happened.
l4_kernel_clock_t next_timeout () const
Get the time for the next timeout.
void handle_expired_timeouts (l4_kernel_clock_t now)
run the callbacks of expired timeouts
void add (Timeout *timeout, l4_kernel_clock_t time)
Add a timeout to the queue.
void remove (Timeout *timeout)
Remove timeout from the queue.
Detailed Description
Timeout queue to be used in l4re server loop.
Definition at line 56 of file ipc_timeout_queue.
Member Function Documentation
void L4::Ipc_svr::Timeout_queue::add (Timeout * timeout, l4_kernel_clock_t time) inline
Add a timeout to the queue.
Parameters
timeout timeout object to add
time the time when the timeout expires
Precondition
timeout must not be in any queue already
Definition at line 118 of file ipc_timeout_queue.
References cxx::Bits::Basic_list< POLICY >::begin(), cxx::Bits::Basic_list< POLICY >::end(), and cxx::H_list< T, POLICY >::insert_before().
Referenced by L4::Ipc_svr::Timeout_queue_hooks< Br_manager_timeout_hooks, Br_manager >::add_timeout().
void L4::Ipc_svr::Timeout_queue::handle_expired_timeouts (l4_kernel_clock_t now) inline
run the callbacks of expired timeouts
Parameters
now the current time.
Definition at line 94 of file ipc_timeout_queue.
References cxx::Bits::Basic_list< POLICY >::begin(), cxx::Bits::Basic_list< POLICY >::empty(), cxx::H_list< T, POLICY >::erase(), and L4::Ipc_svr::Timeout::expired().
Referenced by L4::Ipc_svr::Timeout_queue_hooks< Br_manager_timeout_hooks, Br_manager >::setup_wait().
l4_kernel_clock_t L4::Ipc_svr::Timeout_queue::next_timeout () const inline
Get the time for the next timeout.
Returns
the time for the next timeout or 0 if there is none
Definition at line 85 of file ipc_timeout_queue.
Referenced by L4::Ipc_svr::Timeout_queue_hooks< Br_manager_timeout_hooks, Br_manager >::timeout().
void L4::Ipc_svr::Timeout_queue::remove (Timeout * timeout) inline
Remove timeout from the queue.
Parameters
timeout timeout to remove from timeout queue
Precondition
timeout must be in this queue
Definition at line 134 of file ipc_timeout_queue.
References cxx::Bits::Basic_list< POLICY >::begin(), cxx::Bits::Basic_list< POLICY >::empty(), and cxx::H_list< T, POLICY >::remove().
Referenced by L4::Ipc_svr::Timeout_queue_hooks< Br_manager_timeout_hooks, Br_manager >::remove_timeout().
bool L4::Ipc_svr::Timeout_queue::timeout_expired (l4_kernel_clock_t now) const inline
Determine if a timeout has happened.
Parameters
now the current time.
Returns
true if there is at least one expired timeout in the queue, false if not.
Definition at line 73 of file ipc_timeout_queue.
References cxx::Bits::Basic_list< POLICY >::empty().
Referenced by L4::Ipc_svr::Timeout_queue_hooks< Br_manager_timeout_hooks, Br_manager >::before_reply(), and L4::Ipc_svr::Timeout_queue_hooks< Br_manager_timeout_hooks, Br_manager >::setup_wait().
The documentation for this class was generated from the following file:
l4/cxx/ipc_timeout_queue