L4Re - L4 Runtime Environment: L4::Task Class Reference
L4::Task Class Reference
C++ interface of the Task kernel object.
Public Member Functions
l4_msgtag_t map (Cap< Task > const &src_task, l4_fpage_t const &snd_fpage, l4_addr_t snd_base, l4_utcb_t *utcb=l4_utcb()) throw ()
Map resources available in the source task to a destination task.
l4_msgtag_t unmap (l4_fpage_t const &fpage, l4_umword_t map_mask, l4_utcb_t *utcb=l4_utcb()) throw ()
Revoke rights from the task.
l4_msgtag_t unmap_batch (l4_fpage_t const *fpages, unsigned num_fpages, l4_umword_t map_mask, l4_utcb_t *utcb=l4_utcb()) throw ()
Revoke rights from a task.
l4_msgtag_t delete_obj (L4::Cap< void > obj, l4_utcb_t *utcb=l4_utcb()) throw ()
Release capability and delete object.
l4_msgtag_t release_cap (L4::Cap< void > cap, l4_utcb_t *utcb=l4_utcb()) throw ()
Release capability.
l4_msgtag_t cap_valid (Cap< void > const &cap, l4_utcb_t *utcb=l4_utcb()) throw ()
Test whether a capability selector points to a valid capability.
l4_msgtag_t cap_has_child (Cap< void > const &cap, l4_utcb_t *utcb=l4_utcb()) throw ()
Test whether a capability has child mappings (in another task).
l4_msgtag_t cap_equal (Cap< void > const &cap_a, Cap< void > const &cap_b, l4_utcb_t *utcb=l4_utcb()) throw ()
Test whether two capabilities point to the same object with the same rights.
l4_msgtag_t add_ku_mem (l4_fpage_t const &fpage, l4_utcb_t *utcb=l4_utcb()) throw ()
Add kernel-user memory.
Public Member Functions inherited from L4::Kobject
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Additional Inherited Members
Protected Types inherited from L4::Kobject_t< Task, Kobject, L4_PROTO_TASK, Type_info::Demand_t< 2 > >
typedef Task Class
The target interface type (inheriting from Kobject_t)
typedef Typeid::Iface< PROTO,
Task > __Iface
The interface description for the derived class.
typedef Typeid::Merge_list
< Typeid::Iface_list< __Iface >
, typename
Kobject::__Iface_list > __Iface_list
The list of all RPC interfaces provided directly or through inheritance.
Protected Member Functions inherited from L4::Kobject_t< Task, Kobject, L4_PROTO_TASK, Type_info::Demand_t< 2 > >
L4::Cap< Class > c () const
Get the capability to ourselves.
Protected Member Functions inherited from L4::Kobject
l4_cap_idx_t cap () const throw ()
Return capability selector.
Static Protected Member Functions inherited from L4::Kobject_t< Task, Kobject, L4_PROTO_TASK, Type_info::Demand_t< 2 > >
static void __check_protocols__ ()
Helper to check for protocol conflicts.
Detailed Description
C++ interface of the Task kernel object.
The L4::Task class represents a combination of the address spaces provided by the L4Re micro kernel. A task consists of at least a memory address space and an object address space. On IA32 there is also an IO-port address space associated with an L4::Task.
L4::Task objects are created using the L4::Factory interface.
Include File
#include <l4/sys/task>
Definition at line 43 of file task.
Member Function Documentation
l4_msgtag_t L4::Task::add_ku_mem (l4_fpage_t const & fpage, l4_utcb_t * utcb = l4_utcb()) throw () inline
Add kernel-user memory.
Parameters
fpage Flexpage describing the virtual area the memory goes to.
utcb UTCP pointer of the calling thread.
Returns
Syscall return tag
Definition at line 182 of file task.
References L4::Kobject::cap().
l4_msgtag_t L4::Task::cap_equal (Cap< void > const & cap_a, Cap< void > const & cap_b, l4_utcb_t * utcb = l4_utcb()) throw () inline
Test whether two capabilities point to the same object with the same rights.
Parameters
cap_a First capability selector to compare.
cap_b Second capability selector to compare.
utcb Optiona: UTCB pointer of the calling thread.
Returns
If the label is 1 cap_a and cap_b point to the same object. Otherwise the label is 0.
Definition at line 171 of file task.
References L4::Kobject::cap().
l4_msgtag_t L4::Task::cap_has_child (Cap< void > const & cap, l4_utcb_t * utcb = l4_utcb()) throw () inline
Test whether a capability has child mappings (in another task).
Parameters
cap Capability selector to look up in the destination task.
utcb UTCB pointer of the calling thread.
Returns
If the label is 1 cap has at least one child mapping in another task. Otherwise the label is 0.
Definition at line 158 of file task.
References L4::Kobject::cap().
l4_msgtag_t L4::Task::cap_valid (Cap< void > const & cap, l4_utcb_t * utcb = l4_utcb()) throw () inline
Test whether a capability selector points to a valid capability.
Parameters
cap Capability selector to check for validity.
utcb UTCB pointer of the calling thread.
Returns
If the label is >0 the capability is valid. Otherwise the label is 0.
Definition at line 147 of file task.
References L4::Kobject::cap().
l4_msgtag_t L4::Task::delete_obj (L4::Cap< void > obj, l4_utcb_t * utcb = l4_utcb()) throw () inline
Release capability and delete object.
Parameters
obj Capability selector of the object to delete.
utcb UTCB pointer of the calling thread.
Returns
Syscall return tag
The object will be deleted if the obj has sufficient rights. No error will be reported if the rights are insufficient, however, the capability is removed in all cases.
Definition at line 124 of file task.
References L4::Kobject::cap().
l4_msgtag_t L4::Task::map (Cap< Task > const & src_task, l4_fpage_t const & snd_fpage, l4_addr_t snd_base, l4_utcb_t * utcb = l4_utcb()) throw () inline
Map resources available in the source task to a destination task.
Parameters
src_task Capability selector of the source task.
snd_fpage Send flexpage that describes an area in the address space or object space of the source task.
snd_base Send base that describes an offset in the receive window of the destination task.
utcb UTCB pointer of the calling thread.
Returns
Syscall return tag.
This method allows for asynchronous rights delegation from one task to another. It can be used to share memory as well as to delegate access to objects.
Definition at line 62 of file task.
References L4::Kobject::cap().
l4_msgtag_t L4::Task::release_cap (L4::Cap< void > cap, l4_utcb_t * utcb = l4_utcb()) throw () inline
Release capability.
Parameters
cap Capability selector to release.
utcb UTCB pointer of the calling thread.
Returns
Syscall return tag.
This operation unmaps the capability from this task.
Definition at line 136 of file task.
References L4::Kobject::cap().
l4_msgtag_t L4::Task::unmap (l4_fpage_t const & fpage, l4_umword_t map_mask, l4_utcb_t * utcb = l4_utcb()) throw () inline
Revoke rights from the task.
Parameters
fpage Flexpage that describes an area in the address space or object space of this task
map_mask Unmap mask, see l4_unmap_flags_t
utcb UTCB pointer of the calling thread.
Returns
Syscall return tag
This method allows to revoke rights from the destination task and from all the tasks that got the rights delegated from that task (i.e., this operation does a recursive rights revocation).
Note
If the capability posseses delete rights or if it is the last capability pointing to the object, calling this function might destroy the object itself.
Definition at line 84 of file task.
References L4::Kobject::cap().
l4_msgtag_t L4::Task::unmap_batch (l4_fpage_t const * fpages, unsigned num_fpages, l4_umword_t map_mask, l4_utcb_t * utcb = l4_utcb()) throw () inline
Revoke rights from a task.
Parameters
fpages An array of flexpages. Each item describes an area in the address or object space of this task.
num_fpages Number of fpages in the fpages array.
map_mask Unmap mask, see l4_unmap_flags_t.
utcb UTCB pointer of the calling thread.
This method allows to revoke rights from the destination task and from all the tasks that got the rights delegated from that task (i.e., this operation does a recursive rights revocation).
Precondition
The caller needs to take care that num_fpages is not bigger than L4_UTCB_GENERIC_DATA_SIZE - 2.
Note
If the capability posseses delete rights or if it is the last capability pointing to the object, calling this function might destroy the object itself.
Definition at line 108 of file task.
References L4::Kobject::cap().
The documentation for this class was generated from the following file:
l4/sys/task