L4Re - L4 Runtime Environment: L4vbus::Device Class Reference
L4vbus::Device Class Reference
L4 V-BUS functions
Device on a virtual bus (V-BUS)
Public Member Functions
L4::Cap< Vbus > bus_cap () const
access the V-BUS capability of the underlying virtual bus.
l4vbus_device_handle_t dev_handle () const
access the device handle of this device.
int device_by_hid (Device *child, char const *hid, int depth=L4VBUS_MAX_DEPTH, l4vbus_device_t *devinfo=0) const
Find a device by the HID.
int next_device (Device *child, int depth=L4VBUS_MAX_DEPTH, l4vbus_device_t *devinfo=0) const
Find next child following child.
int get_resource (int res_idx, l4vbus_resource_t *res) const
Iterate over the resources of a device.
int is_compatible (char const *cid) const
Check if the given device has a compatibility ID (CID) or HID that matches cid.
bool operator== (Device const &o) const
Test if two devices are the same V-BUS device.
bool operator!= (Device const &o) const
Test if two devices are not the same.
Public Member Functions inherited from L4vbus::Pm< Device >
int pm_suspend () const
Suspend the module.
int pm_resume () const
Resume the module.
Protected Attributes
L4::Cap< Vbus > _bus
l4vbus_device_handle_t _dev
The device handle for this device.
Detailed Description
Device on a virtual bus (V-BUS)
Definition at line 56 of file vbus.
Member Function Documentation
L4::Cap<Vbus> L4vbus::Device::bus_cap () const inline
access the V-BUS capability of the underlying virtual bus.
Returns
the capability to the underlying V-BUS.
Definition at line 68 of file vbus.
References _bus.
Referenced by L4vbus::Pci_host_bridge::cfg_read(), L4vbus::Pci_dev::cfg_read(), L4vbus::Pci_host_bridge::cfg_write(), L4vbus::Pci_dev::cfg_write(), L4vbus::Pci_host_bridge::irq_enable(), and L4vbus::Pci_dev::irq_enable().
l4vbus_device_handle_t L4vbus::Device::dev_handle () const inline
access the device handle of this device.
Returns
the device handle for this device.
The device handle is used to directly address the device on its virtual bus.
Definition at line 77 of file vbus.
References _dev.
int L4vbus::Device::device_by_hid (Device * child, char const * hid, int depth = L4VBUS_MAX_DEPTH, l4vbus_device_t * devinfo = 0) const inline
Find a device by the HID.
This function searches the vbus for a device with the given HID and returns a handle to the first matching device. The HID usually conforms to an ACPI HID or a Linux device tree compatible ID.
It is possible to have multiple devices with the same HID on a vbus. In order to find all matching devices this function has to be called repeatedly with child pointing to the device found in the previous iteration. The iteration starts at child that might be any device node in the tree.
Parameters
[in,out] child Handle of the device from where in the device tree the search should start. To start searching from the beginning child must be initialized using the default (#L4VBUS_NULL). If a matching device is found its handle is returned through this parameter.
hid HID of the device
depth Maximum depth for the recursive lookup
[out] devinfo Device information structure (might be NULL)
Return values
>= 0 A device with the given HID was found.
-L4_ENODEV No device with the given HID could be found on the vbus.
-L4_ENOENT Invalid or no HID provided.
Definition at line 108 of file vbus.
References _bus, _dev, and l4vbus_get_device_by_hid().
int L4vbus::Device::get_resource (int res_idx, l4vbus_resource_t * res) const inline
Iterate over the resources of a device.
Parameters
[out] res_idx Index of the resource, the number of resources is available in the devinfo from get device functions.
[out] res Descriptor of the resource
Returns
0 on success, else failure
Definition at line 143 of file vbus.
References _bus, _dev, and l4vbus_get_resource().
int L4vbus::Device::is_compatible (char const * cid) const inline
Check if the given device has a compatibility ID (CID) or HID that matches cid.
Parameters
cid the compatibility ID to test
Returns
1 when the given ID (cid) matches this device, 0 when the given ID does not match, <0 on error.
Definition at line 157 of file vbus.
References _bus, _dev, and l4vbus_is_compatible().
int L4vbus::Device::next_device (Device * child, int depth = L4VBUS_MAX_DEPTH, l4vbus_device_t * devinfo = 0) const inline
Find next child following child.
Parameters
child Device to start looking for child devices
depth Depth to look for
[out] devinfo device information (might be NULL)
Returns
0 on success, else failure
Definition at line 126 of file vbus.
References _bus, _dev, and l4vbus_get_next_device().
bool L4vbus::Device::operator!= (Device const & o) const inline
Test if two devices are not the same.
Returns
true if the two devices are different, false else.
Definition at line 173 of file vbus.
References _bus, and _dev.
bool L4vbus::Device::operator== (Device const & o) const inline
Test if two devices are the same V-BUS device.
Returns
true if the two devices are the same, false else.
Definition at line 164 of file vbus.
References _bus, and _dev.
Field Documentation
L4::Cap<Vbus> L4vbus::Device::_bus protected
The V-BUS capability (where this device is located on).
Definition at line 179 of file vbus.
Referenced by bus_cap(), L4vbus::Gpio_pin::config_get(), L4vbus::Gpio_pin::config_pad(), L4vbus::Gpio_module::config_pad(), L4vbus::Gpio_pin::config_pull(), device_by_hid(), L4vbus::Gpio_pin::get(), L4vbus::Gpio_module::get(), get_resource(), is_compatible(), next_device(), operator!=(), operator==(), L4vbus::Gpio_pin::set(), L4vbus::Gpio_module::set(), L4vbus::Gpio_pin::setup(), L4vbus::Gpio_module::setup(), L4vbus::Gpio_pin::to_irq(), and L4vbus::Icu::vicu().
The documentation for this class was generated from the following file:
l4/vbus/vbus