L4Re - L4 Runtime Environment: L4virtio::Svr::Driver_mem_region_t< DATA > Class Template Reference
L4virtio::Svr::Driver_mem_region_t< DATA > Class Template Reference
L4 VIRTIO Interface » L4 VIRTIO Transport Layer
Region of driver memory, that shall be managed locally.
Inherits DATA.
Public Member Functions
Driver_mem_region_t ()
Make default empty memroy region.
Driver_mem_region_t (l4_uint64_t drv_base, l4_uint32_t size, l4_addr_t offset, Ds_cap &&ds)
Make a local memory region for the given driver values.
bool is_writable () const
Flags flags () const
bool empty () const
l4_uint64_t drv_base () const
void * local_base () const
l4_uint32_t size () const
l4_addr_t ds_offset () const
L4::Cap< L4Re::Dataspace > ds () const
bool contains (l4_uint64_t base, l4_uint32_t size) const
Test if the given driver address range is within this region.
template<typename T >
T * local (Ptr< T > p) const
Get the local address for driver address p.
Detailed Description
template<typename DATA>
class L4virtio::Svr::Driver_mem_region_t< DATA >
Region of driver memory, that shall be managed locally.
Template Parameters
DATA Class defining additional information
Definition at line 312 of file l4virtio.
Constructor & Destructor Documentation
template<typename DATA > L4virtio::Svr::Driver_mem_region_t< DATA >::Driver_mem_region_t (l4_uint64_t drv_base, l4_uint32_t size, l4_addr_t offset, Ds_cap && ds) inline
Make a local memory region for the given driver values.
Parameters
drv_base Base address of the memory region used by the driver.
size Size of the memory region.
offset Offset within the data space that is mapped to drv_base within the driver.
ds Data space capability backing the memory.
This constructor attaches the region of given data space to the local address space and stores the corresponding data for later reference.
Definition at line 357 of file l4virtio.
References L4Re::chksys(), L4virtio::Svr::Driver_mem_region_t< DATA >::ds(), L4Re::Dataspace::Stats::flags, L4Re::Dataspace::info(), L4_CAP_FPAGE_RO, L4_CAP_FPAGE_RW, L4_EINVAL, L4_ERANGE, L4_PAGESIZE, l4_round_page(), L4::Ipc::make_cap(), L4Re::Dataspace::Map_rw, L4Re::Rm::Read_only, L4Re::Rm::Search_addr, L4Re::Dataspace::Stats::size, and L4virtio::Svr::Driver_mem_region_t< DATA >::size().
Member Function Documentation
template<typename DATA > bool L4virtio::Svr::Driver_mem_region_t< DATA >::contains (l4_uint64_t base, l4_uint32_t size) const inline
Test if the given driver address range is within this region.
Parameters
base The driver base address.
size The size of the region to lookup.
Returns
true if the given driver address region is contained in this region, false else.
Definition at line 428 of file l4virtio.
template<typename DATA > l4_uint64_t L4virtio::Svr::Driver_mem_region_t< DATA >::drv_base () const inline
Returns
The base address used by the driver.
Definition at line 407 of file l4virtio.
template<typename DATA > L4::Cap<L4Re::Dataspace> L4virtio::Svr::Driver_mem_region_t< DATA >::ds () const inline
Returns
The data space capability for this region.
Definition at line 419 of file l4virtio.
Referenced by L4virtio::Svr::Driver_mem_region_t< DATA >::Driver_mem_region_t().
template<typename DATA > l4_addr_t L4virtio::Svr::Driver_mem_region_t< DATA >::ds_offset () const inline
Returns
The offset within the data space.
Definition at line 416 of file l4virtio.
template<typename DATA > bool L4virtio::Svr::Driver_mem_region_t< DATA >::empty () const inline
Returns
True if the region is empty (size == 0), false else.
Definition at line 403 of file l4virtio.
template<typename DATA > Flags L4virtio::Svr::Driver_mem_region_t< DATA >::flags () const inline
Returns
The flags for this region.
Definition at line 400 of file l4virtio.
template<typename DATA > bool L4virtio::Svr::Driver_mem_region_t< DATA >::is_writable () const inline
Returns
True if the region is writable, false else.
Definition at line 397 of file l4virtio.
template<typename DATA > template<typename T > T* L4virtio::Svr::Driver_mem_region_t< DATA >::local (Ptr< T > p) const inline
Get the local address for driver address p.
Parameters
p Driver address to translate.
Precondition
p must be contained in this region.
Returns
Local address for the given driver address p.
Definition at line 452 of file l4virtio.
References L4virtio::Ptr< T >::get().
Referenced by L4virtio::Svr::Driver_mem_list_t< DATA >::load_desc().
template<typename DATA > void* L4virtio::Svr::Driver_mem_region_t< DATA >::local_base () const inline
Returns
The local base address.
Definition at line 410 of file l4virtio.
template<typename DATA > l4_uint32_t L4virtio::Svr::Driver_mem_region_t< DATA >::size () const inline
Returns
The size of the region in bytes.
Definition at line 413 of file l4virtio.
Referenced by L4virtio::Svr::Driver_mem_region_t< DATA >::Driver_mem_region_t().
The documentation for this class was generated from the following file:
l4/l4virtio/server/l4virtio