L4Re - L4 Runtime Environment: L4::Factory Class Reference
L4::Factory Class Reference
C++ Factory interface to create kernel objects.
Data Structures
struct Lstr
Special type to add a pascal string into the factory create stream.
struct Nil
Special type to add a void argument into the factory create stream.
class S
Stream class for the create() argument stream.
Public Member Functions
S create (Cap< void > target, long obj, l4_utcb_t *utcb=l4_utcb()) throw ()
Generic create call to the factory.
l4_msgtag_t create_task (Cap< Task > const &target_cap, l4_fpage_t const &utcb_area, l4_utcb_t *utcb=l4_utcb()) throw ()
Create a new task.
l4_msgtag_t create_thread (Cap< Thread > const &target_cap, l4_utcb_t *utcb=l4_utcb()) throw ()
Create a new thread.
l4_msgtag_t create_factory (Cap< Factory > const &target_cap, unsigned long limit, l4_utcb_t *utcb=l4_utcb()) throw ()
Create a new factory.
l4_msgtag_t create_gate (Cap< Kobject > const &target_cap, Cap< Thread > const &thread_cap, l4_umword_t label, l4_utcb_t *utcb=l4_utcb()) throw ()
Create a new IPC gate.
l4_msgtag_t create_irq (Cap< Irq >const &target_cap, l4_utcb_t *utcb=l4_utcb()) throw ()
Create a new IRQ.
l4_msgtag_t create_vm (Cap< Vm >const &target_cap, l4_utcb_t *utcb=l4_utcb()) throw ()
Create a new virtual machine.
Public Member Functions inherited from L4::Kobject
l4_msgtag_t dec_refcnt (l4_mword_t diff, l4_utcb_t *utcb=l4_utcb())
Decrement the in kernel reference counter for the object.
Additional Inherited Members
Protected Types inherited from L4::Kobject_t< Factory, Kobject, L4_PROTO_FACTORY >
typedef Factory Class
The target interface type (inheriting from Kobject_t)
typedef Typeid::Iface< PROTO,
Factory > __Iface
The interface description for the derived class.
typedef Typeid::Merge_list
< Typeid::Iface_list< __Iface >
, typename
Kobject::__Iface_list > __Iface_list
The list of all RPC interfaces provided directly or through inheritance.
Protected Member Functions inherited from L4::Kobject_t< Factory, Kobject, L4_PROTO_FACTORY >
L4::Cap< Class > c () const
Get the capability to ourselves.
Protected Member Functions inherited from L4::Kobject
l4_cap_idx_t cap () const throw ()
Return capability selector.
Static Protected Member Functions inherited from L4::Kobject_t< Factory, Kobject, L4_PROTO_FACTORY >
static void __check_protocols__ ()
Helper to check for protocol conflicts.
Detailed Description
C++ Factory interface to create kernel objects.
A factory is used to create all kinds of kernel objects:
L4::Task
L4::Thread
L4::Factory
L4::Ipc_gate
L4::Irq
L4::Vm
The factory is equipped with a limit that limits the amount of kernel memory available to that factory.
Note
The limit does not give any guarantee for the amount of available kernel memory.
Include File
#include <l4/sys/factory>
For the C interface refer to Factory.
Definition at line 54 of file factory.
Member Function Documentation
S L4::Factory::create (Cap< void > target, long obj, l4_utcb_t * utcb = l4_utcb()) throw () inline
Generic create call to the factory.
Parameters
[out] target Capability selector for the new object. The caller must allocate the capability slot. The kernel stores the new objects's capability into this slot.
obj The protocol ID that specifies which kind of object shall be created.
utcb The UTCB to use for the operation.
Returns
A create stream that allows adding additional arguments to the create() call.
This method does currently not directly invoke the factory. It returns a stream that shall invoke the factory after adding all additional arguments.
Usage:
L4::Cap<L4Re::Namespace> ns = L4Re::Util::cap_alloc.alloc<L4Re::Namespace>();
factory->create(ns, L4Re::Namespace::Protocol) << "Argument text";
Definition at line 234 of file factory.
References L4::Kobject::cap().
Referenced by L4Re::Mem_alloc::alloc().
l4_msgtag_t L4::Factory::create_factory (Cap< Factory > const & target_cap, unsigned long limit, l4_utcb_t * utcb = l4_utcb()) throw () inline
Create a new factory.
Parameters
[out] target_cap Capability selector for the root capability of the new factory. The caller must allocate the capability slot. The kernel stores the new factory's capability into this slot.
limit Limit for the new factory in bytes.
utcb The UTCB to use for the operation.
Returns
Syscall return tag
Note
The limit of the new factory is subtracted from the available amount of the factory used for creation.
Definition at line 306 of file factory.
References L4::Kobject::cap(), and l4_factory_create_factory_u().
l4_msgtag_t L4::Factory::create_gate (Cap< Kobject > const & target_cap, Cap< Thread > const & thread_cap, l4_umword_t label, l4_utcb_t * utcb = l4_utcb()) throw () inline
Create a new IPC gate.
Parameters
[out] target_cap Capability selector for the root capability of the new IPC gate. The caller must allocate the capability slot. The kernel stores the new IPC gate's capability into this slot.
thread_cap Capability selector of the thread to bind the gate to.
label Label of the gate.
utcb The UTCB to use for the operation.
Returns
Syscall return tag
See also
L4::Ipc_gate
Definition at line 327 of file factory.
References L4::Kobject::cap(), and l4_factory_create_gate_u().
l4_msgtag_t L4::Factory::create_irq (Cap< Irq >const & target_cap, l4_utcb_t * utcb = l4_utcb()) throw () inline
Create a new IRQ.
Parameters
[out] target_cap Capability selector for the root capability of the new IRQ. The caller must allocate the capability slot. The kernel stores the new IRQ's capability into this slot.
utcb The UTCB to use for the operation.
Returns
Syscall return tag
See also
L4::Irq
Definition at line 345 of file factory.
References L4::Kobject::cap(), and l4_factory_create_irq_u().
l4_msgtag_t L4::Factory::create_task (Cap< Task > const & target_cap, l4_fpage_t const & utcb_area, l4_utcb_t * utcb = l4_utcb()) throw () inline
Create a new task.
Parameters
[out] target_cap Capability selector for the root capability of the new task. The caller must allocate the capability slot. The kernel stores the new task's capability into this slot.
utcb_area Flexpage that describes the area used for UTCBs and vCPU state-save-areas of the new task.
utcb The UTCB to use for the operation.
Returns
Syscall return tag
Note
The size of the UTCB area specifies indirectly the number of UTCBs available for this task. Refer to L4::Task::add_ku_mem / l4_task_add_ku_mem() for adding more of this type of memory.
See also
L4::Task
Definition at line 269 of file factory.
References L4::Kobject::cap(), and l4_factory_create_task_u().
l4_msgtag_t L4::Factory::create_thread (Cap< Thread > const & target_cap, l4_utcb_t * utcb = l4_utcb()) throw () inline
Create a new thread.
Parameters
[out] target_cap Capability selector for the root capability of the new thread. The caller must allocate the capability slot. The kernel stores the new thread's capability into this slot.
utcb The UTCB to use for the operation.
Returns
Syscall return tag
See also
L4::Thread
Definition at line 287 of file factory.
References L4::Kobject::cap(), and l4_factory_create_thread_u().
l4_msgtag_t L4::Factory::create_vm (Cap< Vm >const & target_cap, l4_utcb_t * utcb = l4_utcb()) throw () inline
Create a new virtual machine.
Parameters
[out] target_cap Capability selector for the root capability of the new VM. The caller must allocate the capability slot. The kernel stores the new VM's capability into this slot.
utcb The UTCB to use for the operation.
Returns
Syscall return tag
See also
L4::Vm
Definition at line 362 of file factory.
References L4::Kobject::cap(), and l4_factory_create_vm_u().
The documentation for this class was generated from the following file:
l4/sys/factory