L4Re - L4 Runtime Environment: L4vbus::Pci_host_bridge Class Reference
L4vbus::Pci_host_bridge Class Reference
A Pci host bridge.
Public Member Functions
int cfg_read (l4_uint32_t bus, l4_uint32_t devfn, l4_uint32_t reg, l4_uint32_t *value, l4_uint32_t width) const
Read from the vPCI configuration space using the PCI root bridge.
int cfg_write (l4_uint32_t bus, l4_uint32_t devfn, l4_uint32_t reg, l4_uint32_t value, l4_uint32_t width) const
Write to the vPCI configuration space using the PCI root bridge.
int irq_enable (l4_uint32_t bus, l4_uint32_t devfn, int pin, unsigned char *trigger, unsigned char *polarity) const
Enable PCI interrupt for a specific device using the PCI root bridge.
Public Member Functions inherited from L4vbus::Device
L4::Cap< Vbus > bus_cap () const
access the V-BUS capability of the underlying virtual bus.
l4vbus_device_handle_t dev_handle () const
access the device handle of this device.
int device_by_hid (Device *child, char const *hid, int depth=L4VBUS_MAX_DEPTH, l4vbus_device_t *devinfo=0) const
Find a device by the HID.
int next_device (Device *child, int depth=L4VBUS_MAX_DEPTH, l4vbus_device_t *devinfo=0) const
Find next child following child.
int get_resource (int res_idx, l4vbus_resource_t *res) const
Iterate over the resources of a device.
int is_compatible (char const *cid) const
Check if the given device has a compatibility ID (CID) or HID that matches cid.
bool operator== (Device const &o) const
Test if two devices are the same V-BUS device.
bool operator!= (Device const &o) const
Test if two devices are not the same.
Public Member Functions inherited from L4vbus::Pm< Device >
int pm_suspend () const
Suspend the module.
int pm_resume () const
Resume the module.
Additional Inherited Members
Protected Attributes inherited from L4vbus::Device
L4::Cap< Vbus > _bus
l4vbus_device_handle_t _dev
The device handle for this device.
Detailed Description
A Pci host bridge.
Definition at line 20 of file vbus_pci.
Member Function Documentation
int L4vbus::Pci_host_bridge::cfg_read (l4_uint32_t bus, l4_uint32_t devfn, l4_uint32_t reg, l4_uint32_t * value, l4_uint32_t width) const inline
Read from the vPCI configuration space using the PCI root bridge.
Parameters
bus Bus number
devfn Device id (upper 16bit) and function (lower 16bit)
reg Register in configuration space to read
[out] value Value that has been read
width Width to read in bits (e.g. 8, 16, 32)
Returns
0 on success, else failure
Definition at line 34 of file vbus_pci.
References L4vbus::Device::_dev, L4vbus::Device::bus_cap(), and l4vbus_pci_cfg_read().
int L4vbus::Pci_host_bridge::cfg_write (l4_uint32_t bus, l4_uint32_t devfn, l4_uint32_t reg, l4_uint32_t value, l4_uint32_t width) const inline
Write to the vPCI configuration space using the PCI root bridge.
Parameters
bus Bus number
devfn Device id (upper 16bit) and function (lower 16bit)
reg Register in configuration space to write
value Value to write
width Width to write in bits (e.g. 8, 16, 32)
Returns
0 on success, else failure
Definition at line 53 of file vbus_pci.
References L4vbus::Device::_dev, L4vbus::Device::bus_cap(), and l4vbus_pci_cfg_write().
int L4vbus::Pci_host_bridge::irq_enable (l4_uint32_t bus, l4_uint32_t devfn, int pin, unsigned char * trigger, unsigned char * polarity) const inline
Enable PCI interrupt for a specific device using the PCI root bridge.
Parameters
bus Bus number
devfn Device id (upper 16bit) and function (lower 16bit)
pin Interrupt pin (normally as reported in configuration register INTR)
[out] trigger False if interrupt is level-triggered
[out] polarity True if interrupt is of low polarity
Returns
On success: Interrupt line to be used, else failure
Definition at line 74 of file vbus_pci.
References L4vbus::Device::_dev, L4vbus::Device::bus_cap(), and l4vbus_pci_irq_enable().
The documentation for this class was generated from the following file:
l4/vbus/vbus_pci