L4Re - L4 Runtime Environment: L4Re::Util::Event_buffer_consumer_t< PAYLOAD > Class Template Reference
L4Re::Util::Event_buffer_consumer_t< PAYLOAD > Class Template Reference
L4Re C++ Interface » L4Re Util C++ Interface
An event buffer consumer.
Public Member Functions
template<typename CB , typename D >
void foreach_available_event (CB const &cb, D data=D())
Call function on every available event.
template<typename CB , typename D >
void process (L4::Cap< L4::Irq > irq, L4::Cap< L4::Thread > thread, CB const &cb, D data=D())
Continuously wait for events and process them.
Public Member Functions inherited from L4Re::Util::Event_buffer_t< PAYLOAD >
void * buf () const throw ()
Return the buffer.
long attach (L4::Cap< L4Re::Dataspace > ds, L4::Cap< L4Re::Rm > rm) throw ()
Attach event buffer from address space.
long detach (L4::Cap< L4Re::Rm > rm) throw ()
Detach event buffer from address space.
Public Member Functions inherited from L4Re::Event_buffer_t< PAYLOAD >
Event_buffer_t (void *buffer, l4_addr_t size)
Initialize event buffer.
Event * next () throw ()
Next event in buffer.
bool put (Event const &ev) throw ()
Put event into buffer at current position.
Detailed Description
template<typename PAYLOAD>
class L4Re::Util::Event_buffer_consumer_t< PAYLOAD >
An event buffer consumer.
Definition at line 92 of file event_buffer.
Member Function Documentation
template<typename PAYLOAD > template<typename CB , typename D > void L4Re::Util::Event_buffer_consumer_t< PAYLOAD >::foreach_available_event (CB const & cb, D data = D()) inline
Call function on every available event.
Parameters
cb Function callback.
data Data to pass as an argument to the callback.
Definition at line 103 of file event_buffer.
References L4Re::Event_buffer_t< PAYLOAD >::Event::free().
Referenced by L4Re::Util::Event_buffer_consumer_t< PAYLOAD >::process().
template<typename PAYLOAD > template<typename CB , typename D > void L4Re::Util::Event_buffer_consumer_t< PAYLOAD >::process (L4::Cap< L4::Irq > irq, L4::Cap< L4::Thread > thread, CB const & cb, D data = D()) inline
Continuously wait for events and process them.
Parameters
irq Event signal to wait for.
thread Thread capability of the thread calling this function.
cb Callback function that is called for each received event.
data Data to pass as an argument to the processing callback.
Note
This function never returns.
Definition at line 124 of file event_buffer.
References L4::Irq::attach(), L4Re::Util::Event_buffer_consumer_t< PAYLOAD >::foreach_available_event(), l4_error(), l4_ipc_error(), L4_IPC_NEVER, l4_irq_receive(), and l4_utcb().
The documentation for this class was generated from the following file:
l4/re/util/event_buffer