L4Re - L4 Runtime Environment: L4virtio::Svr::Device_t< DATA > Class Template Reference
L4virtio::Svr::Device_t< DATA > Class Template Reference abstract
L4 VIRTIO Interface » L4 VIRTIO Transport Layer
Server-side L4-VIRTIO device stub.
Public Member Functions
virtual void reset ()=0
reset callback, called for doing a device reset
virtual bool check_queues ()=0
callback for checking if the queues at DRIVER_OK transition
virtual int reconfig_queue (unsigned idx)=0
callback for client queue-config request
virtual void register_single_driver_irq ()=0
callback for registering a singe guest IRQ for all queues
virtual L4::Cap< L4::Irq > device_notify_irq () const =0
callback to gather the device notification IRQ
Device_t (Dev_config *dev_config)
Make a device for the given config.
Mem_list const * mem_info () const
Get the memory region list used for this device.
void reset_queue_config (unsigned idx, unsigned num_max, bool inc_generation=false)
Trigger reset for the configuration space for queue idx.
void init_mem_info (unsigned num)
Initialize the memory region list to the given maximum.
void device_error ()
Transition device into failed state.
bool setup_queue (Virtqueue *q, unsigned qn, unsigned num_max)
Enable/disable the specified queue.
Protected Attributes
Mem_list _mem_info
Memory region list.
Detailed Description
template<typename DATA>
class L4virtio::Svr::Device_t< DATA >
Server-side L4-VIRTIO device stub.
Definition at line 626 of file l4virtio.
Member Function Documentation
template<typename DATA > void L4virtio::Svr::Device_t< DATA >::device_error () inline
Transition device into failed state.
Note
Callers should trigger a guest config IRQ after calling this function.
This function does a full reset, (calls reset()) and sets the failed bit in the device status register.
Definition at line 751 of file l4virtio.
References L4virtio::Svr::Device_t< DATA >::reset(), and L4virtio::Svr::Dev_config::set_failed().
template<typename DATA > void L4virtio::Svr::Device_t< DATA >::init_mem_info (unsigned num) inline
Initialize the memory region list to the given maximum.
Parameters
num Maximum number of memory regions that can be managed.
Definition at line 738 of file l4virtio.
References L4virtio::Svr::Driver_mem_list_t< DATA >::init().
template<typename DATA > void L4virtio::Svr::Device_t< DATA >::reset_queue_config (unsigned idx, unsigned num_max, bool inc_generation = false) inline
Trigger reset for the configuration space for queue idx.
Parameters
idx The queue index to reset.
num_max Maximum number of entries in this queue.
inc_generation The config generation will be incremented when this is true.
This function resets the driver-readable configuration space for the queue with the given index. The queue configuration is reset to all 0, name num_max to the given value.
Definition at line 728 of file l4virtio.
References L4virtio::Svr::Dev_config::reset_queue().
template<typename DATA > bool L4virtio::Svr::Device_t< DATA >::setup_queue (Virtqueue * q, unsigned qn, unsigned num_max) inline
Enable/disable the specified queue.
Parameters
q Pointer to the ring that represents the virtqueue internally.
qn Index of the queue.
num_max Maximum number of supported entries in this queue.
Returns
true for success.
This function calculates the parameters of the virtqueue from the clients configuration space values, checks the accessibility of the queue data structures and initializes q to ready state when all checks succeeded.
Definition at line 770 of file l4virtio.
References l4virtio_config_queue_t::align, L4virtio::Virtqueue::disable(), L4virtio::Svr::Driver_mem_list_t< DATA >::find(), l4virtio_config_hdr_t::guest_page_size, L4virtio::Svr::Dev_config::hdr(), L4_UNLIKELY, l4virtio_config_queue_t::num, l4virtio_config_queue_t::pfn, L4virtio::Svr::Dev_config::qconfig(), L4virtio::Virtqueue::setup(), and L4virtio::Virtqueue::total_size().
The documentation for this class was generated from the following file:
l4/l4virtio/server/l4virtio