L4Re - L4 Runtime Environment: L4virtio::Svr::Request_processor Class Reference
L4virtio::Svr::Request_processor Class Reference
L4 VIRTIO Interface » L4 VIRTIO Transport Layer
Encapsulate the state for processing a VIRTIO request.
Public Member Functions
template<typename DESC_MAN , typename... ARGS>
void start (DESC_MAN *dm, Virtqueue *ring, Virtqueue::Head_desc const &request, ARGS...args)
Start processing a new request.
template<typename DESC_MAN , typename... ARGS>
Virtqueue::Request const & start (DESC_MAN *dm, Virtqueue::Request const &request, ARGS...args)
Start processing a new request.
Virtqueue::Desc::Flags current_flags () const
Get the flags of the currently processed descriptor.
bool has_more () const
Are there more chained descriptors ?
template<typename DESC_MAN , typename... ARGS>
bool next (DESC_MAN *dm, ARGS...args)
Switch to the next descriptor in a descriptor chain.
Detailed Description
Encapsulate the state for processing a VIRTIO request.
A VIRTIO request is a possibly chained list of descriptors retrieved from the available ring of a virtqueue, using Virtqueue::next_avail().
The descriptor processing depends on helper (DESC_MAN) for interpreting the descriptors in the context of the device implementation.
DESC_MAN has to provide the functionality to safely dereference a descriptor from a descriptor list.
The following methods must be provided by DESC_MAN:
DESC_MAN::load_desc(Virtqueue::Desc const &desc,
                    Request_processor const *proc,
                    Virtqueue::Desc const **table)
This function is used to dereference desc as an indirect descriptor table, and must return a pointer to an indirect descriptor table.
DESC_MAN::load_desc(Virtqueue::Desc const &desc,
                    Request_processor const *proc, ...)
This function is used to dereference a descriptor as a normal data buffer, and '...' are the arguments that are passed to start() and next().
Definition at line 360 of file virtio.
Member Function Documentation
Virtqueue::Desc::Flags L4virtio::Svr::Request_processor::current_flags () const inline
Get the flags of the currently processed descriptor.
Returns
The flags of the currently processed descriptor.
Definition at line 424 of file virtio.
References L4virtio::Virtqueue::Desc::flags.
bool L4virtio::Svr::Request_processor::has_more () const inline
Are there more chained descriptors ?
Returns
true if there are more chained descriptors in the current request.
Definition at line 431 of file virtio.
References L4virtio::Virtqueue::Desc::flags, and L4virtio::Virtqueue::Desc::Flags::next().
template<typename DESC_MAN , typename... ARGS> bool L4virtio::Svr::Request_processor::next (DESC_MAN * dm, ARGS... args) inline
Switch to the next descriptor in a descriptor chain.
Template Parameters
DESCM_MAN Type of descriptor manager (implicit).
Parameters
dm Descriptor manager that is used to translate VIRTIO descriptor addresses.
args Extra arguments passed to dm->load_desc()
Returns
true if a descriptor is available, false if not.
Definition at line 442 of file virtio.
References L4virtio::Svr::Bad_descriptor::Bad_flags, L4virtio::Svr::Bad_descriptor::Bad_next, L4virtio::Virtqueue::Desc::flags, L4virtio::Virtqueue::Desc::Flags::indirect(), L4_UNLIKELY, L4virtio::Virtqueue::Desc::Flags::next(), and L4virtio::Virtqueue::Desc::next.
template<typename DESC_MAN , typename... ARGS> void L4virtio::Svr::Request_processor::start (DESC_MAN * dm, Virtqueue * ring, Virtqueue::Head_desc const & request, ARGS... args) inline
Start processing a new request.
Template Parameters
DESCM_MAN Type of descriptor manager (implicit).
Parameters
dm Descriptor manager that is used to translate VIRTIO descriptor addresses.
ring VIRTIO ring of the request.
request VIRTIO request from Virtqueue::next_avail()
args Extra arguments passed to dm->load_desc()
Precondition
The given request must be valid.
Definition at line 383 of file virtio.
References L4virtio::Svr::Bad_descriptor::Bad_size, L4virtio::Svr::Virtqueue::Head_desc::desc(), L4virtio::Svr::Virtqueue::desc(), L4virtio::Virtqueue::Desc::flags, L4virtio::Virtqueue::Desc::Flags::indirect(), L4_UNLIKELY, L4virtio::Virtqueue::Desc::len, and L4virtio::Virtqueue::num().
Referenced by start().
template<typename DESC_MAN , typename... ARGS> Virtqueue::Request const& L4virtio::Svr::Request_processor::start (DESC_MAN * dm, Virtqueue::Request const & request, ARGS... args) inline
Start processing a new request.
Template Parameters
DESCM_MAN Type of descriptor manager (implicit).
Parameters
dm Descriptor manager that is used to translate VIRTIO descriptor addresses.
request VIRTIO request from Virtqueue::next_avail()
args Extra arguments passed to dm->load_desc()
Precondition
The given request must be valid.
Definition at line 414 of file virtio.
References start().
The documentation for this class was generated from the following file:
l4/l4virtio/server/virtio