L4Re - L4 Runtime Environment: L4virtio::Svr::Driver_mem_list_t< DATA > Class Template Reference
L4virtio::Svr::Driver_mem_list_t< DATA > Class Template Reference
L4 VIRTIO Interface » L4 VIRTIO Transport Layer
List of driver memory regions assigned to a single L4-VIRTIO transport instance.
Public Types
typedef L4Re::Util::Auto_cap
< L4Re::Dataspace >::Cap Ds_cap
type for storing a data-space capability internally
Public Member Functions
Driver_mem_list_t ()
Make an empty, zero capacity list.
void init (unsigned max)
Make a fresh list with capacity max.
bool full () const
Mem_region const * add (l4_uint64_t drv_base, l4_uint32_t size, l4_addr_t offset, Ds_cap &&ds)
Add a new region to the list.
void remove (Mem_region const *r)
Remove the given region from the list.
Mem_region const * find (l4_uint64_t base, l4_uint32_t size) const
Find memory region containing the given driver address region.
Mem_region * find (l4_uint64_t base, l4_uint32_t size)
Find memory region containing the given driver address region.
void load_desc (Virtqueue::Desc const &desc, Request_processor const *p, Virtqueue::Desc const **table) const
Default implementation for loading an indirect descriptor.
void load_desc (Virtqueue::Desc const &desc, Request_processor const *p, Mem_region const **data) const
Default implementation returning the Driver_mem_region.
template<typename ARG >
void load_desc (Virtqueue::Desc const &desc, Request_processor const *p, ARG *data) const
Default implementation returning generic information.
Detailed Description
template<typename DATA>
class L4virtio::Svr::Driver_mem_list_t< DATA >
List of driver memory regions assigned to a single L4-VIRTIO transport instance.
Note
The regions added to this list must never overlap.
Definition at line 465 of file l4virtio.
Member Function Documentation
template<typename DATA > Mem_region const* L4virtio::Svr::Driver_mem_list_t< DATA >::add (l4_uint64_t drv_base, l4_uint32_t size, l4_addr_t offset, Ds_cap && ds) inline
Add a new region to the list.
Parameters
drv_base Driver base address of the region.
size Size of the region in bytes.
offset Offset within the data space attached to drv_base.
ds Data space backing the driver memory.
Returns
A pointer to the new region.
Definition at line 505 of file l4virtio.
References L4Re::chksys(), L4virtio::Svr::Driver_mem_list_t< DATA >::full(), and L4_ENOMEM.
template<typename DATA > Mem_region const* L4virtio::Svr::Driver_mem_list_t< DATA >::find (l4_uint64_t base, l4_uint32_t size) const inline
Find memory region containing the given driver address region.
Parameters
base Driver base address.
size Size of the region.
Returns
Pointer to the region containing the given region, NULL if none is found.
Definition at line 539 of file l4virtio.
Referenced by L4virtio::Svr::Driver_mem_list_t< DATA >::load_desc(), and L4virtio::Svr::Device_t< DATA >::setup_queue().
template<typename DATA > Mem_region* L4virtio::Svr::Driver_mem_list_t< DATA >::find (l4_uint64_t base, l4_uint32_t size) inline
Find memory region containing the given driver address region.
Parameters
base Driver base address.
size Size of the region.
Returns
Pointer to the region containing the given region, NULL if none is found.
Definition at line 547 of file l4virtio.
template<typename DATA > bool L4virtio::Svr::Driver_mem_list_t< DATA >::full () const inline
Returns
True if the remaining capacity is 0.
Definition at line 494 of file l4virtio.
Referenced by L4virtio::Svr::Driver_mem_list_t< DATA >::add().
template<typename DATA > void L4virtio::Svr::Driver_mem_list_t< DATA >::init (unsigned max) inline
Make a fresh list with capacity max.
Parameters
max The capacity of this vector.
Definition at line 486 of file l4virtio.
References cxx::max().
Referenced by L4virtio::Svr::Device_t< DATA >::init_mem_info().
template<typename DATA > void L4virtio::Svr::Driver_mem_list_t< DATA >::load_desc (Virtqueue::Desc const & desc, Request_processor const * p, Virtqueue::Desc const ** table) const inline
Default implementation for loading an indirect descriptor.
Parameters
desc The descriptor to load
p The request processor calling us
[out] table Shall be set to the loaded descriptor table
Definition at line 558 of file l4virtio.
References L4virtio::Virtqueue::Desc::addr, L4virtio::Svr::Bad_descriptor::Bad_address, L4virtio::Svr::Driver_mem_list_t< DATA >::find(), L4virtio::Ptr< T >::get(), L4_UNLIKELY, L4virtio::Virtqueue::Desc::len, and L4virtio::Svr::Driver_mem_region_t< DATA >::local().
template<typename DATA > void L4virtio::Svr::Driver_mem_list_t< DATA >::load_desc (Virtqueue::Desc const & desc, Request_processor const * p, Mem_region const ** data) const inline
Default implementation returning the Driver_mem_region.
Parameters
desc The descriptor to load
p The request processor calling us
[out] data Shall be set to a pointer to the Driver_mem_region that covers the descriptor.
Definition at line 575 of file l4virtio.
References L4virtio::Virtqueue::Desc::addr, L4virtio::Svr::Bad_descriptor::Bad_address, L4virtio::Svr::Driver_mem_list_t< DATA >::find(), L4virtio::Ptr< T >::get(), L4_UNLIKELY, and L4virtio::Virtqueue::Desc::len.
template<typename DATA > template<typename ARG > void L4virtio::Svr::Driver_mem_list_t< DATA >::load_desc (Virtqueue::Desc const & desc, Request_processor const * p, ARG * data) const inline
Default implementation returning generic information.
Template Parameters
ARG Abstract argument type used with Request_processor::start() and Request_processor::next() to deliver the result of loading a descriptor. This type must provide a constructor taking three arguments: (1) pointer to a Driver_mem_region, (2) the Virtqueue::Desc descriptor, and (3) a pointer to the calling Request_processor.
Parameters
desc The descriptor to load
p The request processor calling us
[out] data Shall be assigned to ARG(mem, desc, p)
Definition at line 598 of file l4virtio.
References L4virtio::Virtqueue::Desc::addr, L4virtio::Svr::Bad_descriptor::Bad_address, L4virtio::Svr::Driver_mem_list_t< DATA >::find(), L4virtio::Ptr< T >::get(), L4_UNLIKELY, and L4virtio::Virtqueue::Desc::len.
template<typename DATA > void L4virtio::Svr::Driver_mem_list_t< DATA >::remove (Mem_region const * r) inline
Remove the given region from the list.
Parameters
r The region to remove (result from add(), or find()).
Definition at line 519 of file l4virtio.
References L4Re::chksys(), and L4_ERANGE.
The documentation for this class was generated from the following file:
l4/l4virtio/server/l4virtio