L4Re - L4 Runtime Environment: L4Re::Util::Event_t< PAYLOAD > Class Template Reference
L4Re::Util::Event_t< PAYLOAD > Class Template Reference
Convenience wrapper for getting access to an event object.
Public Types
enum Mode { Mode_irq, Mode_polling }
Modes of operation.
Public Member Functions
template<typename IRQ_TYPE >
int init (L4::Cap< L4Re::Event > event, L4Re::Env const *env=L4Re::Env::env(), L4Re::Cap_alloc *ca=L4Re::Cap_alloc::get_cap_alloc(L4Re::Util::cap_alloc))
Initialise an event object.
int init_poll (L4::Cap< L4Re::Event > event, L4Re::Env const *env=L4Re::Env::env(), L4Re::Cap_alloc *ca=L4Re::Cap_alloc::get_cap_alloc(L4Re::Util::cap_alloc))
Initialise an event object in polling mode.
L4Re::Event_buffer_t< PAYLOAD > & buffer ()
Get event buffer.
L4::Cap< L4::Triggerable > irq () const
Get event IRQ.
Detailed Description
template<typename PAYLOAD>
class L4Re::Util::Event_t< PAYLOAD >
Convenience wrapper for getting access to an event object.
After calling init() the class supplies the event-buffer and the associated IRQ object.
Definition at line 41 of file event.
Member Enumeration Documentation
template<typename PAYLOAD > enum L4Re::Util::Event_t::Mode
Modes of operation.
Enumerator
Mode_irq
Create an IRQ and attach, to get notifications.
Mode_polling
Do not use an IRQ.
Definition at line 47 of file event.
Member Function Documentation
template<typename PAYLOAD > L4Re::Event_buffer_t<PAYLOAD>& L4Re::Util::Event_t< PAYLOAD >::buffer () inline
Get event buffer.
Returns
Event buffer object.
Definition at line 156 of file event.
template<typename PAYLOAD > template<typename IRQ_TYPE > int L4Re::Util::Event_t< PAYLOAD >::init (L4::Cap< L4Re::Event > event, L4Re::Env const * env = L4Re::Env::env(), L4Re::Cap_alloc * ca = L4Re::Cap_alloc::get_cap_alloc(L4Re::Util::cap_alloc)) inline
Initialise an event object.
Template Parameters
IRQ_TYPE Type used for handling notifications from the event provider. This must be derived from L4::Triggerable.
Parameters
event Capability to event.
env Pointer to L4Re-Environment
ca Pointer to capability allocator.
Return values
0 Success
-L4_ENOMEM No memory to allocate required capabilities.
<0 Other IPC errors.
Definition at line 68 of file event.
References L4::Icu::bind(), L4Re::Event::get_buffer(), L4_ENOMEM, l4_error(), L4::Ipc::make_cap_rw(), and L4Re::Rm::Search_addr.
template<typename PAYLOAD > int L4Re::Util::Event_t< PAYLOAD >::init_poll (L4::Cap< L4Re::Event > event, L4Re::Env const * env = L4Re::Env::env(), L4Re::Cap_alloc * ca = L4Re::Cap_alloc::get_cap_alloc(L4Re::Util::cap_alloc)) inline
Initialise an event object in polling mode.
Parameters
event Capability to event.
env Pointer to L4Re-Environment
ca Pointer to capability allocator.
Return values
0 Success
-L4_ENOMEM No memory to allocate required capabilities.
<0 Other IPC errors.
Definition at line 121 of file event.
References L4Re::Event::get_buffer(), L4_ENOMEM, L4::Ipc::make_cap_rw(), and L4Re::Rm::Search_addr.
template<typename PAYLOAD > L4::Cap<L4::Triggerable> L4Re::Util::Event_t< PAYLOAD >::irq () const inline
Get event IRQ.
Returns
Event IRQ.
Definition at line 163 of file event.
The documentation for this class was generated from the following file:
l4/re/util/event