L4Re - L4 Runtime Environment: L4virtio::Svr::Virtqueue Class Reference
L4virtio::Svr::Virtqueue Class Reference
L4 VIRTIO Interface » L4 VIRTIO Transport Layer
Virtqueue implementation for the device.
Data Structures
class Head_desc
VIRTIO request, essentially a descriptor from the available ring.
Public Member Functions
Request next_avail ()
Get the next available descriptor from the available ring.
bool desc_avail () const
Test for available descriptors.
void consumed (Head_desc const &r, l4_uint32_t len=0)
Put the given descriptor into the used ring.
void disable_notify ()
Set the 'no notify' flag for this queue.
void enable_notify ()
Clear the 'no notify' flag for this queue.
Desc const * desc (unsigned idx) const
Get a descriptor from the descriptor list.
Public Member Functions inherited from L4virtio::Virtqueue
void disable ()
Completely disable the queue.
unsigned long total_size (unsigned num, l4_uint32_t align) const
Calculate the total size for a virtqueue of the given dimensions.
unsigned long total_size () const
Calculate the total size of this virtqueue.
void setup (unsigned num, l4_uint32_t align, void *base)
Enable this queue.
void dump (Desc const *d) const
Dump descriptors for this queue.
bool ready () const
Test if this queue is in working state.
unsigned num () const
bool no_notify_guest () const
Get the no IRQ flag of this queue.
bool no_notify_host () const
Get the no notify flag of this queue.
void no_notify_host (bool value)
Set the no-notify flag for this queue.
Additional Inherited Members
Protected Member Functions inherited from L4virtio::Virtqueue
Virtqueue ()
Create a disabled virtqueue.
Protected Attributes inherited from L4virtio::Virtqueue
Desc * _desc
pointer to descriptor table, NULL if queue is off.
Avail * _avail
pointer to available ring.
Used * _used
pointer to used ring.
l4_uint16_t _current_avail
The life counter for the queue.
l4_uint16_t _idx_mask
mask used for indexing into the descriptor table and the rings.
Detailed Description
Virtqueue implementation for the device.
This class represents a single virtqueue, with a local running available index.
Definition at line 92 of file virtio.
Member Function Documentation
void L4virtio::Svr::Virtqueue::consumed (Head_desc const & r, l4_uint32_t len = 0) inline
Put the given descriptor into the used ring.
Parameters
r request that shall be marked as finished.
len the total number of bytes written.
Precondition
queue must be in working state.
r must be a valid request from this queue.
Definition at line 171 of file virtio.
References L4virtio::Virtqueue::_desc, L4virtio::Virtqueue::_idx_mask, L4virtio::Virtqueue::_used, L4virtio::Virtqueue::Used::idx, and L4virtio::Virtqueue::Used::ring.
Desc const* L4virtio::Svr::Virtqueue::desc (unsigned idx) const inline
Get a descriptor from the descriptor list.
Parameters
idx the index of the descriptor.
Precondition
idx < num
queue must be in working state
Definition at line 216 of file virtio.
References L4virtio::Virtqueue::_desc.
Referenced by L4virtio::Svr::Request_processor::start().
bool L4virtio::Svr::Virtqueue::desc_avail () const inline
Test for available descriptors.
Returns
true if there are descriptors availabale, false if not.
Precondition
The queue must be in working state.
Definition at line 159 of file virtio.
References L4virtio::Virtqueue::_avail, L4virtio::Virtqueue::_current_avail, and L4virtio::Virtqueue::Avail::idx.
void L4virtio::Svr::Virtqueue::disable_notify () inline
Set the 'no notify' flag for this queue.
This function may be called on a disabled queue.
Definition at line 193 of file virtio.
References L4virtio::Virtqueue::_used, L4virtio::Virtqueue::Used::flags, L4_LIKELY, L4virtio::Virtqueue::Used::Flags::no_notify(), and L4virtio::Virtqueue::ready().
void L4virtio::Svr::Virtqueue::enable_notify () inline
Clear the 'no notify' flag for this queue.
This function may be called on a disabled queue.
Definition at line 204 of file virtio.
References L4virtio::Virtqueue::_used, L4virtio::Virtqueue::Used::flags, L4_LIKELY, L4virtio::Virtqueue::Used::Flags::no_notify(), and L4virtio::Virtqueue::ready().
Request L4virtio::Svr::Virtqueue::next_avail () inline
Get the next available descriptor from the available ring.
Precondition
The queue must be in working state.
Returns
A Request for the next available descriptor, the Request is invalid if there are no descriptors in the available ring.
Note
The return value must be checked even when a previous desc_avail() returned true.
Definition at line 142 of file virtio.
References L4virtio::Virtqueue::_avail, L4virtio::Virtqueue::_current_avail, L4virtio::Virtqueue::_idx_mask, L4virtio::Virtqueue::Avail::idx, L4_LIKELY, and L4virtio::Virtqueue::Avail::ring.
The documentation for this class was generated from the following file:
l4/l4virtio/server/virtio