L4Re - L4 Runtime Environment: Small C++ Template Library
Small C++ Template Library
Namespaces
cxx
Our C++ library.
Data Structures
class L4::Alloc_list
A simple list-based allocator.
class cxx::Auto_ptr< T >
Smart pointer with automatic deletion.
class cxx::Bitmap_base
Basic bitmap abstraction.
class cxx::Bitmap_base::Bit
A writeable bit in a bitmap.
class cxx::Bitmap_base::Word< BITS >
Helper abstraction for a word contained in the bitmap.
class cxx::Bitmap_base::Char< BITS >
Helper abstraction for a byte contained in the bitmap.
class cxx::Bitmap< BITS >
A static bit map.
class cxx::List_item
Basic list item.
class cxx::List_item::Iter
Iterator for a list of ListItem-s.
class cxx::List_item::T_iter< T, Poly >
Iterator for derived classes from ListItem.
struct cxx::Pair< First, Second >
Pair of two values.
class cxx::Base_slab< Obj_size, Slab_size, Max_free, Alloc >
Basic slab allocator.
class cxx::Slab< Type, Slab_size, Max_free, Alloc >
Slab allocator for object of type Type.
class cxx::Base_slab_static< Obj_size, Slab_size, Max_free, Alloc >
Merged slab allocator (allocators for objects of the same size are merged together).
class cxx::Slab_static< Type, Slab_size, Max_free, Alloc >
Merged slab allocator (allocators for objects of the same size are merged together).
class cxx::Nothrow
Helper type to distinguish the oeprator new version that does not throw exceptions.
class cxx::New_allocator< _Type >
Standard allocator based on operator new () .
class L4::String
A null-terminated string container class.
Enumerations
enum { cxx::Bitmap_base::W_bits = sizeof(word_type) * 8, cxx::Bitmap_base::C_bits = 8 }
enum { cxx::Base_slab< Obj_size, Slab_size, Max_free, Alloc >::object_size = Obj_size, cxx::Base_slab< Obj_size, Slab_size, Max_free, Alloc >::slab_size = Slab_size, cxx::Base_slab< Obj_size, Slab_size, Max_free, Alloc >::objects_per_slab = (Slab_size - sizeof(Slab_head)) / object_size, cxx::Base_slab< Obj_size, Slab_size, Max_free, Alloc >::max_free_slabs = Max_free }
enum { cxx::Base_slab_static< Obj_size, Slab_size, Max_free, Alloc >::object_size = Obj_size, cxx::Base_slab_static< Obj_size, Slab_size, Max_free, Alloc >::slab_size = Slab_size, cxx::Base_slab_static< Obj_size, Slab_size, Max_free, Alloc >::objects_per_slab = _A::objects_per_slab, cxx::Base_slab_static< Obj_size, Slab_size, Max_free, Alloc >::max_free_slabs = Max_free }
Functions
template<typename T1 >
T1 cxx::min (T1 a, T1 b)
Get the minimum of a and b.
template<typename T1 >
T1 cxx::max (T1 a, T1 b)
Get the maximum of a and b.
void * operator new (size_t, void *mem, cxx::Nothrow const &) throw ()
Simple placement new operator.
void * operator new (size_t, cxx::Nothrow const &) throw ()
New operator that does not throw exceptions.
Detailed Description
Enumeration Type Documentation
anonymous enum protected
Enumerator
W_bits
number of bits in word_type
C_bits
number of bits in char
Definition at line 38 of file bitmap.
template<int Obj_size, int Slab_size = L4_PAGESIZE, int Max_free = 2, template< typename A > class Alloc = New_allocator> anonymous enum
Enumerator
object_size
size of an object.
slab_size
size of a slab cache.
objects_per_slab
objects per slab cache.
max_free_slabs
maximum number of free slab caches.
Definition at line 63 of file slab_alloc.
template<int Obj_size, int Slab_size = L4_PAGESIZE, int Max_free = 2, template< typename A > class Alloc = New_allocator> anonymous enum
Enumerator
object_size
size of an object.
slab_size
size of a slab cache.
objects_per_slab
number of objects per slab cache.
max_free_slabs
maximum number of free slab caches.
Definition at line 355 of file slab_alloc.
Function Documentation
template<typename T1 > T1 cxx::max (T1 a, T1 b) inline
Get the maximum of a and b.
Parameters
a the first value.
b the second value.
Definition at line 45 of file minmax.
Referenced by cxx::List_alloc::alloc_max(), L4::Scheduler::info(), L4virtio::Svr::Driver_mem_list_t< DATA >::init(), and L4::Type_info::Demand::operator|().
template<typename T1 > T1 cxx::min (T1 a, T1 b) inline
Get the minimum of a and b.
Parameters
a the first value.
b the second value.
Examples:
tmpfs/lib/src/fs.cc.
Definition at line 35 of file minmax.
Referenced by L4virtio::Svr::Data_buffer::copy_to(), and L4virtio::Svr::Data_buffer::skip().
void* operator new (size_t , void * mem, cxx::Nothrow const &) throw () inline
Simple placement new operator.
Parameters
mem the address of the memory block to place the new object.
Returns
the address given by mem.
Definition at line 39 of file std_alloc.