L4Re - L4 Runtime Environment: Platform Control C API
Platform Control C API
Base API » Kernel Objects
C interface for controlling platform-wide properties.
Functions
l4_msgtag_t l4_platform_ctl_system_suspend (l4_cap_idx_t pfc, l4_umword_t extras) L4_NOTHROW
Enter suspend to RAM.
l4_msgtag_t l4_platform_ctl_system_shutdown (l4_cap_idx_t pfc, l4_umword_t reboot) L4_NOTHROW
Shutdown or reboot the system.
l4_msgtag_t l4_platform_ctl_cpu_enable (l4_cap_idx_t pfc, l4_umword_t phys_id) L4_NOTHROW
Enable an offline CPU.
l4_msgtag_t l4_platform_ctl_cpu_disable (l4_cap_idx_t pfc, l4_umword_t phys_id) L4_NOTHROW
Disable an online CPU.
Detailed Description
C interface for controlling platform-wide properties.
Add
#include <l4/sys/platform_control.h>
to your code to use the platform control functions. The API allows a client to suspend, reboot or shutdown the system.
For the C++ interface refer to L4::Platform_control
Function Documentation
l4_msgtag_t l4_platform_ctl_cpu_disable (l4_cap_idx_t pfc, l4_umword_t phys_id) inline
Disable an online CPU.
Parameters
pfc Capability to the platform control object.
phys_id Physical CPU id of CPU (e.g. local APIC id) to disable.
Returns
System call message tag
Definition at line 231 of file platform_control.h.
References l4_utcb().
l4_msgtag_t l4_platform_ctl_cpu_enable (l4_cap_idx_t pfc, l4_umword_t phys_id) inline
Enable an offline CPU.
Parameters
pfc Capability to the platform control object.
phys_id Physical CPU id of CPU (e.g. local APIC id) to enable.
Returns
System call message tag
Definition at line 224 of file platform_control.h.
References l4_utcb().
l4_msgtag_t l4_platform_ctl_system_shutdown (l4_cap_idx_t pfc, l4_umword_t reboot) inline
Shutdown or reboot the system.
Parameters
pfc Capability selector for the platform-control object
reboot Shutdown when 0, or reboot when 1.
Returns
Syscall return tag
Definition at line 193 of file platform_control.h.
References l4_utcb().
l4_msgtag_t l4_platform_ctl_system_suspend (l4_cap_idx_t pfc, l4_umword_t extras) inline
Enter suspend to RAM.
Parameters
pfc Capability selector for the platform-control object
extras some extra platform-specific information needed to enter suspend to RAM.
Returns
Syscall return tag
Definition at line 186 of file platform_control.h.
References l4_utcb().