L4Re - L4 Runtime Environment: Kernel Debugger
Kernel Debugger
Base API » Fiasco extensions
Kernel debugger related functionality.
Macros
#define enter_kdebug(text)
Enter L4 kernel debugger.
#define asm_enter_kdebug(text)
Enter L4 kernel debugger (plain assembler version)
#define kd_display(text)
Show message with L4 kernel debugger, but do not enter debugger.
#define ko(c)
Output character with L4 kernel debugger.
#define enter_kdebug(text)
Enter L4 kernel debugger.
#define asm_enter_kdebug(text)
Enter L4 kernel debugger (plain assembler version)
#define kd_display(text)
Show message with L4 kernel debugger, but do not enter debugger.
#define ko(c)
Output character with L4 kernel debugger.
Functions
l4_msgtag_t l4_debugger_set_object_name (l4_cap_idx_t cap, const char *name) L4_NOTHROW
Set the name of a kernel object.
unsigned long l4_debugger_global_id (l4_cap_idx_t cap) L4_NOTHROW
Get the globally unique ID of the object behind a capability.
unsigned long l4_debugger_kobj_to_id (l4_cap_idx_t cap, l4_addr_t kobjp) L4_NOTHROW
Get the globally unique ID of the object behind the kobject pointer.
void outchar (char c) L4_NOTHROW
Print character.
void outstring (const char *text) L4_NOTHROW
Print character string.
void outnstring (char const *text, unsigned len) L4_NOTHROW
Print character string.
void outhex32 (int number) L4_NOTHROW
Print 32 bit number (hexadecimal)
void outhex20 (int number) L4_NOTHROW
Print 20 bit number (hexadecimal)
void outhex16 (int number) L4_NOTHROW
Print 16 bit number (hexadecimal)
void outhex12 (int number) L4_NOTHROW
Print 12 bit number (hexadecimal)
void outhex8 (int number) L4_NOTHROW
Print 8 bit number (hexadecimal)
void outdec (int number) L4_NOTHROW
Print number (decimal)
char l4kd_inchar (void) L4_NOTHROW
Read character from console, non blocking.
Detailed Description
Kernel debugger related functionality.
Attention
This API is subject to change!
This is a debugging facility, any call to any function might be invalid. Do not rely on it in any real code.
Include File
#include <l4/sys/debugger.h>
Macro Definition Documentation
#define asm_enter_kdebug (text)
Value:
"int  $3  \n\t"\
    "jmp  1f  \n\t"\
    ".ascii \"" text "\"\n\t"\
    "1:     \n\t"
Enter L4 kernel debugger (plain assembler version)
Parameters
text Text to be shown at kernel debugger prompt
Definition at line 63 of file kdebug.h.
#define asm_enter_kdebug (text)
Value:
"int  $3  \n\t"\
    "jmp  1f  \n\t"\
    ".ascii \"" text "\"\n\t"\
    "1:     \n\t"
Enter L4 kernel debugger (plain assembler version)
Parameters
text Text to be shown at kernel debugger prompt
Definition at line 63 of file kdebug.h.
#define enter_kdebug (text)
Value:
asm(\
    "int  $3  \n\t"\
    "jmp  1f  \n\t"\
    ".ascii \"" text "\"\n\t"\
    "1:     \n\t"\
    )
Enter L4 kernel debugger.
Parameters
text Text to be shown at kernel debugger prompt
Examples:
examples/sys/singlestep/main.c.
Definition at line 41 of file kdebug.h.
Referenced by fiasco_tbuf_get_status_phys().
#define enter_kdebug (text)
Value:
asm(\
    "int  $3  \n\t"\
    "jmp  1f  \n\t"\
    ".ascii \"" text "\"\n\t"\
    "1:     \n\t"\
    )
Enter L4 kernel debugger.
Parameters
text Text to be shown at kernel debugger prompt
Definition at line 41 of file kdebug.h.
#define kd_display (text)
Value:
asm(\
    "int  $3  \n\t"\
    "nop    \n\t"\
    "jmp  1f  \n\t"\
    ".ascii \"" text "\"\n\t"\
    "1:     \n\t"\
    )
Show message with L4 kernel debugger, but do not enter debugger.
Parameters
text Text to be shown
Definition at line 76 of file kdebug.h.
#define kd_display (text)
Value:
asm(\
    "int  $3  \n\t"\
    "nop    \n\t"\
    "jmp  1f  \n\t"\
    ".ascii \"" text "\"\n\t"\
    "1:     \n\t"\
    )
Show message with L4 kernel debugger, but do not enter debugger.
Parameters
text Text to be shown
Definition at line 76 of file kdebug.h.
#define ko (c)
Value:
asm(\
      "int  $3  \n\t"     \
      "cmpb %0,%%al \n\t"     \
      : /* No output */       \
      : "N" (c)         \
      )
Output character with L4 kernel debugger.
Parameters
c Character to be shown
Definition at line 92 of file kdebug.h.
#define ko (c)
Value:
asm(\
      "int  $3  \n\t"     \
      "cmpb %0,%%al \n\t"     \
      : /* No output */       \
      : "N" (c)         \
      )
Output character with L4 kernel debugger.
Parameters
c Character to be shown
Definition at line 92 of file kdebug.h.
Function Documentation
unsigned long l4_debugger_global_id (l4_cap_idx_t cap) inline
Get the globally unique ID of the object behind a capability.
Parameters
cap Capability
Return values
~0UL Capability is not valid.
>=0 Global debugger id.
This is a debugging facility, the call might be invalid.
Definition at line 331 of file debugger.h.
References l4_utcb().
unsigned long l4_debugger_kobj_to_id (l4_cap_idx_t cap, l4_addr_t kobjp) inline
Get the globally unique ID of the object behind the kobject pointer.
Parameters
cap Capability
kobjp Kobject pointer
Return values
~0UL The capability or the kobject pointer are invalid.
>=0 The globally unique id.
This is a debugging facility, the call might be invalid.
Definition at line 337 of file debugger.h.
References l4_utcb().
l4_msgtag_t l4_debugger_set_object_name (l4_cap_idx_t cap, const char * name) inline
Set the name of a kernel object.
Parameters
cap Capability which refers to the kernel object.
name Name of the kernel object that is e.g. displayed in the kernel debugger.
This is a debugging facility, the call might be invalid.
Examples:
examples/sys/aliens/main.c.
Definition at line 324 of file debugger.h.
References l4_utcb().
char l4kd_inchar (void) inline
Read character from console, non blocking.
Returns
Input character, -1 if no character to read
Definition at line 369 of file kdebug.h.
void outchar (char c) inline
Print character.
Parameters
c Character
Definition at line 263 of file kdebug.h.
void outdec (int number) inline
Print number (decimal)
Parameters
number Number
Definition at line 358 of file kdebug.h.
void outhex12 (int number) inline
Print 12 bit number (hexadecimal)
Parameters
number 12 bit number
Definition at line 336 of file kdebug.h.
void outhex16 (int number) inline
Print 16 bit number (hexadecimal)
Parameters
number 16 bit number
Definition at line 325 of file kdebug.h.
void outhex20 (int number) inline
Print 20 bit number (hexadecimal)
Parameters
number 20 bit number
Definition at line 314 of file kdebug.h.
void outhex32 (int number) inline
Print 32 bit number (hexadecimal)
Parameters
number 32 bit number
Definition at line 303 of file kdebug.h.
void outhex8 (int number) inline
Print 8 bit number (hexadecimal)
Parameters
number 8 bit number
Definition at line 347 of file kdebug.h.
void outnstring (char const * text, unsigned len) inline
Print character string.
Parameters
text Character string
len Number of characters
text String
len Number of characters
Examples:
examples/sys/aliens/main.c.
Definition at line 288 of file kdebug.h.
void outstring (const char * text) inline
Print character string.
Parameters
text Character string
text String
Examples:
examples/sys/aliens/main.c.
Definition at line 275 of file kdebug.h.