L4Re - L4 Runtime Environment: L4 Namespace Reference
L4 Namespace Reference
L4 low-level kernel interface.
Namespaces
Ipc
IPC related functionality.
Ipc_svr
Helper classes for L4::Server instantiation.
Typeid
Definition of interface data-type helpers.
Types
L4 basic type helpers for C++.
Data Structures
class Alloc_list
A simple list-based allocator.
class Base_exception
Base class for all exceptions, thrown by the L4Re framework.
class Basic_registry
This registry returns the corresponding server object based on the label of an Ipc_gate.
class Bounds_error
Access out of bounds.
class Cap
C++ interface for capabilities.
class Com_error
Error conditions during IPC.
class Debugger
C++ debugger interface.
class Element_already_exists
Exception for duplicate element insertions.
class Element_not_found
Exception for a failed lookup (element not found).
class Exception_tracer
Back-trace support for exceptions.
class Factory
C++ Factory interface to create kernel objects.
class Icu
C++ Icu interface.
class Invalid_capability
Indicates that an invalid object was invoked.
class Iommu
Interface for IO-MMUs used for DMA remapping.
class IOModifier
Modifier class for the IO stream.
class Ipc_gate
The C++ IPC gate interface.
class Irq
C++ Irq interface.
class Irq_eoi
Interface for sending an acknowledge message to an object.
struct Irq_handler_object
Server object base class for handling IRQ messages.
struct Irq_mux
IRQ multiplexer for shared IRQs.
class Kobject
Base class for all kinds of kernel objects and remote objects, referenced by capabilities.
class Kobject_2t
Helper class to create an L4Re interface class that is derived from two base classes (see L4::Kobject_t).
struct Kobject_3t
Helper class to create an L4Re interface class that is derived from three base classes (see L4::Kobject_t).
struct Kobject_demand
Get the combined server-side resource requirements for all type T...
class Kobject_t
Helper class to create an L4Re interface class that is derived from a single base class.
struct Kobject_typeid
Meta object for handling access to type information of Kobjects.
struct Kobject_x
Generic Kobject inheritance template.
class Out_of_memory
Exception signalling insufficient memory.
class Platform_control
L4 C++ interface for controlling platform-wide properties.
class Poll_timeout_kipclock
A polling timeout based on the L4Re clock.
struct Proto_t
Data type for defining protocol numbers.
class Runtime_error
Exception for an abstract runtime error.
class Scheduler
Scheduler object.
struct Semaphore
Kernel-provided semaphore object.
class Server
Basic server loop for handling client requests.
class Server_object
Abstract server object to be used with L4::Server and L4::Basic_registry.
struct Server_object_t
Base class (template) for server implementing server objects.
struct Server_object_x
Helper class to implement p_dispatch based server objects.
class Smart_cap
Smart capability class.
class String
A null-terminated string container class.
class Task
C++ interface of the Task kernel object.
class Thread
C++ L4 kernel thread interface.
struct Triggerable
Interface that allows an object to be triggered by some source.
struct Type_info
Dynamic Type Information for L4Re Interfaces.
class Unknown_error
Exception for an unknown condition.
class Vcon
C++ L4 Vcon interface.
class Vm
Virtual machine.
Typedefs
typedef int Opcode
Data type for RPC opcodes.
Enumerations
enum { PROTO_ANY = 0, PROTO_EMPTY = -19 }
Functions
template<typename T >
Type_info const * kobject_typeid ()
Get the L4::Type_info for the L4Re interface given in T.
template<typename T , typename F >
Cap< T > cap_dynamic_cast (Cap< F > const &c) throw ()
dynamic_cast for capabilities.
template<typename T , typename F >
Cap< T > cap_cast (Cap< F > const &c) throw ()
static_cast for capabilities.
template<typename T , typename F >
Cap< T > cap_reinterpret_cast (Cap< F > const &c) throw ()
reinterpret_cast for capabilities.
template<typename T , typename F , typename SMART >
Smart_cap< T, SMART > cap_cast (Smart_cap< F, SMART > const &c) throw ()
static_cast for capabilities.
template<typename T , typename F , typename SMART >
Smart_cap< T, SMART > cap_reinterpret_cast (Smart_cap< F, SMART > const &c) throw ()
reinterpret_cast for capabilities.
void throw_ipc_exception (L4::Cap< void > const &o, l4_msgtag_t const &err, l4_utcb_t *utcb)
Throw an L4 IPC error as exception.
void throw_ipc_exception (void const *o, l4_msgtag_t const &err, l4_utcb_t *utcb)
Throw an L4 IPC error as exception.
Variables
IOModifier const hex
Modifies the stream to print numbers as hexadecimal values.
IOModifier const dec
Modifies the stream to print numbers as decimal values.
BasicOStream cout
Standard output stream.
BasicOStream cerr
Standard error stream.
Detailed Description
L4 low-level kernel interface.
Enumeration Type Documentation
anonymous enum
Enumerator
PROTO_ANY
Default protocol used by Kobject_t and Kobject_x.
PROTO_EMPTY
Empty protocol for empty APIs.
Definition at line 55 of file __typeinfo.h.
Function Documentation
template<typename T , typename F > Cap<T> L4::cap_cast (Cap< F > const & c) throw () inline
static_cast for capabilities.
Template Parameters
T The target type of the capability
F The source type (and is usually implicitly set)
Parameters
c The source capability that shall be casted
Returns
A capability typed to the interface T.
The use of this cast operator is similar to the static_cast<>() for C++ pointers. It does the same type checking and adjustments like C++ does on pointers.
Example code:
L4::Cap<L4::Kobject> obj = ... ;
L4::Cap<L4::Icu> icu = L4::cap_cast<L4::Icu>(obj);
Definition at line 356 of file capability.h.
Referenced by L4Re::Cap_alloc::alloc(), L4Re::Util::Counting_cap_alloc< COUNTERTYPE >::alloc(), and L4::Ipc_svr::Server_iface::rcv_cap().
template<typename T , typename F > Cap<T> L4::cap_dynamic_cast (Cap< F > const & c) throw () inline
dynamic_cast for capabilities.
Template Parameters
T is the target type of the capability
F is the source type (and is usually implicitly set)
Parameters
c is the source capability that shall be casted
Returns
A capability typed to the interface T. If the object does not support the target interface T or does not support the L4::Meta interface the result is the invalid capability selector.
The use of this cast operator is similar to the dynamic_cast<>() for C++ pointers. It also induces overhead, because it uses the meta interface (L4::Meta) to do runtime type checking.
Example code:
L4::Cap<L4::Kobject> obj = ... ;
L4::Cap<L4::Icu> icu = L4::cap_dynamic_cast<L4::Icu>(obj);
Definition at line 110 of file capability.
References cap_reinterpret_cast(), and l4_error().
template<typename T , typename F > Cap<T> L4::cap_reinterpret_cast (Cap< F > const & c) throw () inline
reinterpret_cast for capabilities.
Template Parameters
T The target type of the capability
F The source type (and is usually implicitly set)
Parameters
c The source capability that shall be casted
Returns
A capability typed to the interface T.
The use of this cast operator is similar to the reinterpret_cast<>() for C++ pointers. It does not do any type checking or type adjustment.
Example code:
L4::Cap<L4::Kobject> obj = ... ;
L4::Cap<L4::Icu> icu = L4::cap_reinterpret_cast<L4::Icu>(obj);
Definition at line 387 of file capability.h.
Referenced by cap_dynamic_cast().
void L4::throw_ipc_exception (L4::Cap< void > const & o, l4_msgtag_t const & err, l4_utcb_t * utcb) inline
Throw an L4 IPC error as exception.
Parameters
o The client side object, for which the IPC was invoked.
err The IPC result code (error code).
utcb UTCB to be used for this operation, usually the UTCB of the calling thread.
Definition at line 44 of file ipc_helper.
References l4_msgtag_t::has_error().
Referenced by throw_ipc_exception().
void L4::throw_ipc_exception (void const * o, l4_msgtag_t const & err, l4_utcb_t * utcb) inline
Throw an L4 IPC error as exception.
Parameters
o The client side object, for which the IPC was invoked.
err The IPC result code (error code).
utcb UTCB to be used for this operation, usually the UTCB of the calling thread.
Definition at line 61 of file ipc_helper.
References throw_ipc_exception().