L4Re - L4 Runtime Environment: L4Re Namespace Reference
L4Re Namespace Reference
L4Re C++ Interfaces.
Namespaces
Vfs
Virtual file system for interfaces POSIX libc.
Data Structures
class Cap_alloc
Capability allocator interface.
class Console
Console class.
class Dataspace
Interface for memory-like objects.
class Debug_obj
Debug interface.
class Dma_space
DMA Address Space.
class Env
Initial Environment (C++ version).
class Event
Event class.
class Event_buffer_t
Event buffer class.
class Inhibitor
Set of inhibitor locks, which inhibit specific actions when held.
class Log
Log interface class.
class Mem_alloc
Memory allocation interface.
class Namespace
Name-space interface.
class Parent
Parent interface.
class Rm
Region map.
class Smart_cap_auto
Helper for Auto_cap and Auto_del_cap.
Functions
long chksys (long err, char const *extra="", long ret=0)
Generate C++ exception on error.
long chksys (l4_msgtag_t const &t, char const *extra="", l4_utcb_t *utcb=l4_utcb(), long ret=0)
Generate C++ exception on error.
long chksys (l4_msgtag_t const &t, l4_utcb_t *utcb, char const *extra="")
Generate C++ exception on error.
template<typename T >
T chkcap (T &&cap, char const *extra="", long err=-L4_ENOMEM)
Check for valid capability or raise C++ exception.
Detailed Description
L4Re C++ Interfaces.
L4 Runtime Environment.
Function Documentation
template<typename T > T L4Re::chkcap (T && cap, char const * extra = "", long err = -L4_ENOMEM) inline
Check for valid capability or raise C++ exception.
Template Parameters
T Type of object to check, must be capability-like (L4::Cap, L4Re::Util::Auto_cap etc.)
Parameters
cap Capability value to check.
extra Optional text for exception.
err Error value for exception or 0 if the capability value should be used.
This function checks whether the capability is valid. If the capability is invalid an C++ exception is generated, using err if err is not zero, otherwise the capability value is used. A valid capability will just be returned.
Definition at line 139 of file error_helper.
References L4_UNLIKELY.
Referenced by L4virtio::Svr::Dev_config::Dev_config().
long L4Re::chksys (long err, char const * extra = "", long ret = 0) inline
Generate C++ exception on error.
Parameters
err Error value, if negative exception will be thrown
extra Optional text for exception (default "")
ret Optional value for exception, default is error value (err)
This function throws an exception if the err is negative and otherwise returns err.
Definition at line 62 of file error_helper.
References L4_UNLIKELY.
Referenced by L4virtio::Svr::Driver_mem_list_t< DATA >::add(), chksys(), L4virtio::Svr::Dev_config::Dev_config(), L4virtio::Svr::Driver_mem_region_t< DATA >::Driver_mem_region_t(), and L4virtio::Svr::Driver_mem_list_t< DATA >::remove().
long L4Re::chksys (l4_msgtag_t const & t, char const * extra = "", l4_utcb_t * utcb = l4_utcb(), long ret = 0) inline
Generate C++ exception on error.
Parameters
t Message tag.
extra Optional text for exception (default "")
utcb Option UTCB
ret Optional value for exception, default is error value (err)
This function throws an exception if the message tag contains an error or the label in the message tag is negative. Otherwise the label in the message tag is returned.
Definition at line 83 of file error_helper.
References l4_msgtag_t::has_error(), L4_UNLIKELY, and l4_msgtag_t::label().
long L4Re::chksys (l4_msgtag_t const & t, l4_utcb_t * utcb, char const * extra = "") inline
Generate C++ exception on error.
Parameters
t Message tag.
utcb UTCB.
extra Optional text for exception (default "")
This function throws an exception if the message tag contains an error or the label in the message tag is negative. Otherwise the label in the message tag is returned.
Definition at line 106 of file error_helper.
References chksys().